-- ─────────────────────────────────────────────────────────────────
-- Seed: Default transition types
-- ─────────────────────────────────────────────────────────────────
INSERT INTO transitions (name) VALUES
  ('Tech to PM'),('PM - PM'),('Business Analyst to PM'),('APM to PM'),
  ('Product Owner to PM'),('Product Analyst to PM'),('PM to SPM'),
  ('Cofounder to PM'),('Marketing to PM'),('Consultant to PM'),
  ('Fresher to PM'),('APM to APM'),('QA to PM'),('SPM to PM'),
  ('Project Management to PM'),('Customer Success to APM'),('Research to PM'),
  ('PM Intern to APM'),('SPM to Lead PM'),('Data Analyst to PM'),
  ('Career Gap to PM'),('Design to PM'),('HR - PM'),('Product Associate to PM')
ON CONFLICT (name) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────
-- Seed: Placement records (migrated from original SEED array)
-- ─────────────────────────────────────────────────────────────────
INSERT INTO placements (name, linkedin, prev_company, prev_role, new_company, new_role, transition, review, highlight) VALUES
('Swapnali Kamble','https://www.linkedin.com/in/swapnali-kamble/','Jio','PM','Ingram Micro','TPM','PM - PM','Excellent','testimonial'),
('Shreyas Sridhar','https://www.linkedin.com/in/shreyas-sridhar-450b60ba/','twid','PM','Tarabut Gateway','PM','PM - PM','',''),
('Anubhav Routray','https://www.linkedin.com/in/anubhav-routray-51b99799/','Flipkart','Product Analyst','Purplle','PM','Product Analyst to PM','',''),
('Radhynesh Meshram','https://www.linkedin.com/in/radhynesh-meshram/','NHSRCL','Developer','Jai Kisan','PM','Tech to PM','Excellent',''),
('Umang Kelani','https://www.linkedin.com/in/umang-kelani/','Bitwise Inc','Programmer','Meesho','PM','Tech to PM','',''),
('Ruchir Jain','https://www.linkedin.com/in/ruchirjain7/','Wipro','Product Owner','Byju''s','PM','Product Owner to PM','',''),
('Tanu Agarwal','https://www.linkedin.com/in/tanuagarwal/','Accenture','QA Engineer','Shiprocket','PM','QA to PM','',''),
('Lavesh Dalmiya','https://www.linkedin.com/in/laveshdalmiya/','Milkbasket','Product Analyst','LohonoStays','PM','Product Analyst to PM','',''),
('Amogh Raghuram','https://www.linkedin.com/in/amogh-raghuram/','SGGSC','Senior Software Engineer','Intugine','APM','Tech to PM','',''),
('Gaurry Sharma','https://www.linkedin.com/in/gaurrysharma/','Lean Apps','Product Owner','Tookitaki','PM','Product Owner to PM','Excellent',''),
('Nishu Suryavanshi','https://www.linkedin.com/in/nishu-suryavanshi-98824b111/','Concerto.ai','SPM','Airtel','PM','SPM to PM','',''),
('Pragya Sharma','https://www.linkedin.com/in/pragya-sharma-489422101/','Hubilo','Solutions consultant','Almabase','Associate Product Manager','Consultant to PM','Excellent',''),
('Rahul Sharma','https://www.linkedin.com/in/rahulsharmamyteam11/','MyTeam11','PM','MyTeam11','Sr. Product Manager','PM to SPM','',''),
('Rahul Gupta','https://www.linkedin.com/in/rahulgupta450/','Realty Assistant','Product owner','Manipal Groups','PM','Product Owner to PM','',''),
('Manpreet Kaur','https://www.linkedin.com/in/manpreet-kaur-b7555331/','AppViewX','Product Owner','Planview','PM','Product Owner to PM','Excellent',''),
('Sandeep Mohanty','','','MBA Student','Songdew','PM','Fresher to PM','',''),
('Akankshya Mishra','https://www.linkedin.com/in/akankshya-mishra/','Flipkart','PM','eBay','PM','PM - PM','',''),
('Aaquib Al Hossain','https://www.linkedin.com/in/aaquibalhossain','Razorpay','PM','OneMuthoot','PM','PM - PM','',''),
('Rajasree P','https://www.linkedin.com/in/rajasreep','Airtel Payment bank','PM','Paysafe Group','PM','PM - PM','',''),
('Abhishek B','https://www.linkedin.com/in/abhishekb10','HDFC','PM','Novac Technology Solutions','PM','PM - PM','',''),
('Siddhartha Barua','https://www.linkedin.com/in/sidbaruaofficial/','Flipkart','PM','Simple','PM','PM - PM','',''),
('Vaishakh Menon','https://www.linkedin.com/in/vaishakh-menon-2b19051a/','Dibiz Global','PM','Jio Mart','PM','PM - PM','Excellent',''),
('Swati Shetty','https://www.linkedin.com/in/swati-shetty-b443a7160','Victoria''s Secret','Product Analyst','Seven Eleven','Senior Product Owner','Product Analyst to PM','Excellent',''),
('Abhay Sakharkar','https://www.linkedin.com/in/abhaysakharkar/','Bajaj Markets','SPM','Bajaj Markets','Lead Product Manager','SPM to Lead PM','Excellent',''),
('BK Koushik','https://www.linkedin.com/in/bkkoushik/','Techmobius','Senior Business Analyst','A-Max Insurance','PM','Business Analyst to PM','',''),
('Rahul Chopra','https://www.linkedin.com/in/rahulchopra29/','ProjectHero','APM','ProjectHero','PM','APM to PM','',''),
('Rajat Aggarwaall','https://www.linkedin.com/in/raggarwal7/','Better.com','Senior Data Analyst','Housing.com','Lead Product Manager','Data Analyst to PM','',''),
('Mrunalini Ukande','https://www.linkedin.com/in/mrunaliniukande/','FinIQ Consulting','Technical Consultant','imagine.io','PM','Tech to PM','',''),
('Karupa Swamy','https://www.linkedin.com/in/karupa017/','Sure Prep','Senior Business Analyst','Thomson Reuters','APM','Business Analyst to PM','',''),
('Akshaya','https://www.linkedin.com/in/akshayavm/','Wrky.ai','Co-founder','EventHQ','Product Head','Cofounder to PM','',''),
('Abdul Hameed','https://www.linkedin.com/in/abdul-hameed-b538991a5/','DigiVal IT Solutions','Test Engineer','COMM-IT','APM','Tech to PM','Average',''),
('Avinash Nadh','https://www.linkedin.com/in/avinash-nadh-739918144/','ZIGRAM','Product Owner','Ikarus 3D','Technical Product Manager','Product Owner to PM','Excellent',''),
('Bishal Chakraborty','https://www.linkedin.com/in/bishal-chakraborty-a5899a211/','—','Student','Hyperverge','Product Intern','Fresher to PM','',''),
('Swapnil Kasera','https://www.linkedin.com/in/swapnil-kasera/','Alma Better','Data Science Trainee','Real Me','PM','Tech to PM','',''),
('Gowthaam','https://www.linkedin.com/in/gowthaam-kumarasamy/','Infosys','Senior System Engineer','Cyces Innovation Labs','APM','Tech to PM','Excellent',''),
('Samyak Krishna','https://www.linkedin.com/in/samyak-krishna/','Architectcube','Product Analyst','Kaagaz','APM','Product Analyst to PM','',''),
('Tejas Mirge','https://www.linkedin.com/in/tejasmirge/','Tech learn live','Campus Leader','Kaazam','APM','Fresher to PM','',''),
('Suman Sahu','https://www.linkedin.com/in/suman-sahu-1891b0191/','Monotype solutions','Market Intelligence Trainee','Droom','APM','Marketing to PM','',''),
('Rajashekara','https://www.linkedin.com/in/rajashekara-d-r/','Mukunda Foods','R&D Engineer','Wysa','Product Manager','Research to PM','',''),
('Rakshit Kumar','https://www.linkedin.com/in/rakshith-kumar-29a8a8179/','Needle','Co-Founder','Riskcovry','Product Management Trainee','Cofounder to PM','',''),
('Cicilia','https://www.linkedin.com/in/ciciliadsouza/','HCL Tech','Software Engineer','Riskcovry','PM Intern','Tech to PM','Excellent',''),
('Abhilash','https://www.linkedin.com/in/abhilash-h/','DailyRounds / Marrow','Senior QA Engineer','Decentro','Product Intern','QA to PM','Excellent',''),
('Nikhil Mondkar','https://www.linkedin.com/in/nikhil-mondkar/','Airpay','Project Management Intern','Swiggy','PM','Project Management to PM','',''),
('Rohit Kumar','https://www.linkedin.com/in/rohit-kumar-18b9b3145/','Dailyhunt','APM','Upswing Financial Technologies','PM','APM to PM','',''),
('Prajwal MG','https://www.linkedin.com/in/prajwal-m-g-3bb693114/','One','PM','Vidyut-tech','PM','PM - PM','',''),
('Rohan Nagarad','https://www.linkedin.com/in/rohanns/','Timely AI','PM','First Advantage','PM','PM - PM','',''),
('Sudripto','https://www.linkedin.com/in/sudripto-khasnabis-459bb18a/','Hexagon Capability Center','Senior Software Engineer','Elemica','Product Analyst','Tech to PM','Excellent',''),
('Devayush','https://www.linkedin.com/in/simplydevayush/','Techstride','Marketing Specialist','Riskcovry','Product Management Trainee','Marketing to PM','',''),
('Manik Mahajan','https://www.linkedin.com/in/manik-m2000/','Eclerx Services','Senior Analyst','Digital Technology Ltd','UI/UX Developer','Business Analyst to PM','',''),
('Akhil Bhatt','https://www.linkedin.com/in/akhil-bhatt-383a741b2/','Cashfree Payments','SDE 1','Hyperbots System','APM','Tech to PM','',''),
('Pranjal Pushp Singh','https://www.linkedin.com/in/pranjalpushpsingh/','Tekion Corp','Product Manager','Brane Enterprises','PM','PM - PM','Excellent','testimonial'),
('Ganpati','https://www.linkedin.com/in/ganapathi-kakkirala/','Data Cult','APM','Cloud SEK','APM','APM to PM','',''),
('Zaid Ahmed','https://www.linkedin.com/in/zaid-ahmed-42306784/','CIMET','Business Analyst','CIMET','PO','Business Analyst to PM','',''),
('Medhansh Jain','https://www.linkedin.com/in/medhanshjain/','VIT Vellore','Student','Hitwicket','PM Intern','Fresher to PM','',''),
('Sagnika Chakraborty','https://www.linkedin.com/in/sagnika/','Vestago Innovations','Co-founder','uExcelerate','PM','Cofounder to PM','',''),
('Jinesh KJ','https://www.linkedin.com/in/kjjinesh/','IBM','Application Developer','Worxogo','APM','Tech to PM','',''),
('Chinmay Pathak','https://www.linkedin.com/in/chinmaypathak2410/','The Rank Group','R&D Analyst','Whatfix','APM','Research to PM','',''),
('Manik Mahajan','https://www.linkedin.com/in/manik-m2000/','Outbox Labs','APM','Grip Invest','APM','APM to PM','',''),
('Ritesh Deshpande','https://www.linkedin.com/in/ritesh-deshpande/','Juniper Networks','Test Engineer 2','Coverstack','APM','Tech to PM','',''),
('Vansh Sethi','https://www.linkedin.com/in/vansh-sethi-93851619b/','Revolo Infotech','Project Manager','POP','PM','Project Management to PM','',''),
('Suruchi Kumari','https://www.linkedin.com/in/suruchi30/','Sonata Software','Digital Engineer','Kristalball','Product Intern','Tech to PM','',''),
('Vaishnav Gangamwar','https://www.linkedin.com/in/vaigan/','—','Career gap','Statiq','PM Intern','Career Gap to PM','',''),
('Kartik Kakkar','https://www.linkedin.com/in/kartik-kakar','Sportskeeda','APM','India Today','APM','APM to APM','',''),
('Abhishek Wabale','https://www.linkedin.com/in/abhishek-wabale-a7b322189/','Bitzetta Technologies','Consultant','Travelxp','Product Trainee','Consultant to PM','',''),
('Sukrit Bhattacharya','https://www.linkedin.com/in/sukrit-bhattacharya/','Happy Locate','SDE Intern','Auditoria AI','PM','Tech to PM','',''),
('Kanupriya','https://www.linkedin.com/in/kanupriya54299-kp/','Ignite Exim','Market Research Analyst','Matiks','Growth PM','Marketing to PM','',''),
('Aman Pande','https://www.linkedin.com/in/aman-pande-a25623155/','Infosys','Product Analyst','JVFPL','PM','Product Analyst to PM','',''),
('Saransh Dimri','https://www.linkedin.com/in/saransh-dimri/','Congruex','Automation Developer','Smart Codes','PM','Tech to PM','',''),
('Aakash','https://www.linkedin.com/in/aakash-ganesh-4120a3180','Razorpay','Senior Product Analyst','Yubi','PM','Product Analyst to PM','Excellent',''),
('Aaron Pacheco','https://www.linkedin.com/in/aaron-pacheco-89b55a140/','InterviewReady','Growth PM','InterviewReady','PM','PM - PM','',''),
('Aarushi Mathur','https://www.linkedin.com/in/aarushi-mathur-90a0191b9/','LocaGlobe','Digital Marketing Intern','Girnar Care','Associate Product Intern','Marketing to PM','',''),
('Abhilash Acharya','https://www.linkedin.com/in/abhilash-h/','DailyRounds / Marrow','Senior QA Engineer','Decentro','Product Intern','QA to PM','',''),
('Abhishek','https://linkedin.com/in/abhishekduragkar','MyCaptain','APM','MyCaptain','PM','APM to PM','',''),
('Abhishek Kori','https://www.linkedin.com/in/abhishekori/','JPMC','Associate Software Engineer','JPMC','PM','Tech to PM','',''),
('Abhishek Shetty','https://www.linkedin.com/in/abhishek-shetty-651aab108/','My Operator','APM','My Operator','PM','APM to PM','Excellent',''),
('Aditi Upadhyay','https://www.linkedin.com/in/aditi-upadhyay-01a16997/','Spenvo','PM','Sambanova','SPM','PM to SPM','Bad',''),
('Aditya','https://www.linkedin.com/in/misterhegde','Amagi Corporation','Senior DevOps Engineer','InSynk Studios','APM','Tech to PM','',''),
('Aditya Kumar','https://www.linkedin.com/in/codeiriss/','Bobble AI','APM','PhysicsWallah','Product - Revenue','APM to PM','',''),
('Aditya Mishra','https://www.linkedin.com/in/aditya-mishra-575b7a179/','Sprinklr','Product','Grip','Product','PM - PM','Excellent',''),
('Akshat Sharma','https://www.linkedin.com/in/akshat8966/','QL Coaching','PM Intern','QL Coaching','APM','PM Intern to APM','Average',''),
('Akshay Tari','https://www.linkedin.com/in/akshay-tari-05a667196/','PowerPlay','PM Intern','AICAN','PM','PM Intern to APM','Average',''),
('Aman Gupta','https://www.linkedin.com/in/amangpt/','Cardgenic','APM','Stashfin','PM','APM to PM','',''),
('Aman Kedia','https://www.linkedin.com/in/aman-kedia-67a73ab4/','FlyFin AI','PM','Zoomcars','PM','PM - PM','Bad',''),
('Anchal Dhariya','https://www.linkedin.com/in/anchal-dhariya-0b596b179/','Bosch Global Software','Business Analyst','Bosch Global Software Technologies','PM','Business Analyst to PM','',''),
('Angel Tawade','https://www.linkedin.com/in/angel-tawade-1028bb129/','TATA AIG','PM','Sail Point','PM','PM - PM','Bad',''),
('Anindya Shankar Dash','https://www.linkedin.com/in/anindyasdash','HighRadius','Senior Product Analyst','ZoomInfo','Data PM','Product Analyst to PM','',''),
('Aniruddha Patil','https://www.linkedin.com/in/apateq/','Freshkart','Founder','Toppr','Product and Growth','Cofounder to PM','',''),
('Anita Majhi','https://www.linkedin.com/in/anitamajhi/','Dell','PM','Dell','PM','PM - PM','',''),
('Anjali','https://www.linkedin.com/in/anjali-thacker/','CloudSEK','Customer Success Manager','CloudSEK','APM','Customer Success to APM','Excellent',''),
('Ankababu','https://www.linkedin.com/in/ankababu-peddisetty-9711b224/','Drink Prime','PM','DrinkPrime','SPM','PM to SPM','',''),
('Ankit Karwa','https://www.linkedin.com/in/ankit-karwa/','Saveo','PM','SupplyNote','SPM','PM to SPM','',''),
('Anmol Jain','https://www.linkedin.com/in/anmol-jain-/','Flink','Co-Founder','Tartan','PM','Cofounder to PM','',''),
('Anuj Singhal','https://www.linkedin.com/in/singhalanuj91/','Realme','Manager - Product Strategy','IndiaMART','Product Manager - Category','Cofounder to PM','Excellent',''),
('Anurag Agarwal','https://www.linkedin.com/in/nov28anurag/','Microsoft','Tech PM','Microsoft','Senior Tech PM','PM to SPM','Excellent',''),
('Aparupa Banerjee','https://www.linkedin.com/in/a-banerjee/','Infosys','Product Owner','Accenture','PM','Product Owner to PM','',''),
('Arsh Akhtar Ansari','https://www.linkedin.com/in/arsha14/','Zing Bus','APM','Shipsy','APM','APM to APM','',''),
('Ashish Raina','https://www.linkedin.com/in/rainaar','DXC','IT Transformation Project Manager','EY','Digital Product Engagement Manager','Project Management to PM','',''),
('Atul Yadav','https://linkedin.com/in/yadav-atul','Frontrow','Product and Growth','Supertails','APM','Product Owner to PM','',''),
('Aznan Ahmed Khan','https://www.linkedin.com/in/aznan-ahmed-khan-869865160/','10 minute school','Lead PM','ShopUp','PM','PM - PM','',''),
('Bhanushree P','https://www.linkedin.com/in/bhanushree','Practicality','Product Owner','InterviewReady','PM','Product Owner to PM','',''),
('Chiranjib Bhattacharjee','https://www.linkedin.com/in/chiranjibjuxlri','TCS','Product Consultant','TCS','Lead PM','Consultant to PM','Excellent',''),
('Devarshi Rawat','https://www.linkedin.com/in/devarshi-rawat-10','TCS','Business Analyst','Marsh McLennan','PM','Business Analyst to PM','Bad',''),
('Dharamjeet Singh','https://www.linkedin.com/in/dharamjeet-singh-46a111105/','YabX','APM','CarDekho','PM','APM to PM','Excellent',''),
('Farhan Ali','https://www.linkedin.com/in/farhanali123/','WebEngage','PM','Dream11','SPM','PM to SPM','',''),
('Ganesh Kumar','https://www.linkedin.com/in/ganesh-kumar-222265176/','Onmobile','PM','TVS','PM','PM - PM','',''),
('Hamsika Yamavaram','https://www.linkedin.com/in/hamsika-y-9a1aa127/','Modak','Business Analyst','LeaderJam','PM','Business Analyst to PM','',''),
('Harish Menon','https://www.linkedin.com/in/harish-menon/','KPMG','Consultant','Tekion Corp','PM','Consultant to PM','',''),
('Harsha Ketaraju','https://www.linkedin.com/in/harsha-ketaraju','IBM','SDE','Ouro','PM','Tech to PM','',''),
('Hemanth Kumar K','https://www.linkedin.com/in/hemanthkempanna/','Motorola','PM-2','Nutanix','SPM','PM to SPM','',''),
('Hrishi','https://www.linkedin.com/in/hrishi-swaroop-bhatnagar/','OYO','PM','Jobizo','SPM','PM to SPM','',''),
('Ishita Gupta','https://www.linkedin.com/in/ishitagupta06','Airtel','PM','Ring','SPM','PM to SPM','',''),
('Jayaraman Krishnan','https://www.linkedin.com/in/imjayaramankrishnan/','Digital JayaRaman','Digital Marketing Specialist','Sip Academy','PM','Marketing to PM','',''),
('Jayasree S','https://www.linkedin.com/in/jayasree-s-70423413/','Trianz','PM','Trianz','PM','PM - PM','Excellent',''),
('Jignesh','https://linkedin.com/in/jigneshjp','Newfold Digital','Web Services Specialist','Valuepitch','PM','Tech to PM','',''),
('Kashif Shaikh','https://www.linkedin.com/in/kashif-shaikh-606449229','Purple Talk','APM','HDFC Life','PM','APM to PM','Excellent',''),
('Likith S','https://www.linkedin.com/in/likith-s','Crito','Customer Support','Bhive','APM','Customer Success to APM','Excellent',''),
('Mayank Verma','https://www.linkedin.com/in/mayank-verma-b80505143/','Times Internet','Customer Success Engineer','Times Internet','APM','Tech to PM','Excellent',''),
('Mirza Mehdi','https://linkedin.com/in/mirza-mehdi','Procter & Gamble','Senior IT Business Analyst','Richmond Hill Public Lib','Digital PM','Business Analyst to PM','',''),
('Navtesh Verma','https://www.linkedin.com/in/navtesh-verma-a20487104/','Synamedia','Global Digital Marketing Manager','RentoMojo','Product - Digital Marketing Manager','Marketing to PM','',''),
('Nayan Bobal','https://www.linkedin.com/in/nayan-bobal','Stanza Living','PM','Tally','PM','PM - PM','',''),
('Pavitra Shetty','https://www.linkedin.com/in/pavitra-s-shetty/','Marsh McLennan','Senior Business Analyst','Accenture','PM','Business Analyst to PM','',''),
('Pooja Punekar','http://linkedin.com/in/pooja-punekar-11435348','CSG','Product Owner','Amadeus','PM','Product Owner to PM','',''),
('Poulomi Kha','https://www.linkedin.com/in/poulomikha/','Censa','PM','Smallcase','PM','PM - PM','',''),
('Priya Gupta','http://linkedin.com/in/priya-gupta1994','APS','Product Associate','HCLTech','APM','Product Associate to PM','',''),
('Rajat Aggarwal','https://www.linkedin.com/in/raggarwal7/','Better.com','Senior Data Analyst','Housing.com','Lead Product Manager','SPM to PM','',''),
('Rashi Arora','https://www.linkedin.com/in/rashiarora17','VMware','Product Owner','Aventra','PM','Product Owner to PM','',''),
('Ravideep Singh','https://www.linkedin.com/in/ravideepsingh12094','EZE Software','Business Analyst','EZE Software','APM','Business Analyst to PM','',''),
('Richa Sinha','https://www.linkedin.com/in/richasinha11/','Credable','APM','SirionLabs','APM','APM to APM','',''),
('Ritika Siraj','https://www.linkedin.com/in/ritika-siraj-249a56123/','HighRadius','APM','Franklin Templeton','PM','APM to PM','',''),
('Rohan Nagarad','https://www.linkedin.com/in/rohan-nagarad-s-9347a6160/','TimelyAI','PM','First Advantage','PM','PM - PM','Average',''),
('Rohit','https://www.linkedin.com/in/rohit-kumar-18b9b3145/','ZOZO Day','APM','Upswing Financial Technologies','PM','APM to PM','Excellent',''),
('Rupak Sahu','https://www.linkedin.com/in/rupaksahu1406/','Abaqus','Product Analyst','Abaqus','APM','Product Analyst to PM','Excellent',''),
('Sagnik Saha','https://www.linkedin.com/in/sagnik411/','Google','Tech PM','Intuit','SPM','PM to SPM','Bad',''),
('Saparja Dey','https://www.linkedin.com/in/saparjadey/','Saviynt','Product Owner','Ping Identity','Tech PM','Product Owner to PM','Bad',''),
('Sarthak Das','https://www.linkedin.com/in/sarthakdas99','TrruckBook','PM Intern','SIXT R&D India','PM 1','PM Intern to APM','',''),
('Shashank Shubham','https://www.linkedin.com/in/shashank-shubham/','Chainalytics','Associate Consultant','Zelthy','APM','Consultant to PM','',''),
('Shrikant','https://www.linkedin.com/in/shrikant-mirji','TCS','System Engineer','TCS Ion','PM','Tech to PM','Excellent',''),
('Shrinidhi M','https://www.linkedin.com/in/shrinidhim/','MedLink Jobs','PM','MedLink Jobs','PM','PM - PM','',''),
('Simranjeet Singh','https://www.linkedin.com/in/simranjeet-j-singh/','AVE-Promagne','HR Intern','Carscan','PM 1','HR - PM','Average',''),
('Siva Karupa','https://www.linkedin.com/in/karupa017','SUREPREP','Senior Business Analyst','Thomson Reuters','APM','Business Analyst to PM','',''),
('Snehil Jain','https://www.linkedin.com/in/snehiljain04/','Accenture','SDE 2','Gheg','PM','Tech to PM','Excellent',''),
('Soumyajyoti Mukherjee','https://www.linkedin.com/in/soumyajyoti-mukherjee/','Punar','Cofounder','Refyne India','PM','Cofounder to PM','',''),
('Sreeja Haridas','https://www.linkedin.com/in/sreeja-haridas-b0469b196/','Emoha','PM','Emoha','SPM','PM to SPM','',''),
('Sri Vishnu','https://www.linkedin.com/in/sri-vishnu-s','B&S Engg','Design Engineer','Visualyze.AI','PM','Design to PM','',''),
('Suchita Khalane','https://www.linkedin.com/in/suchita-khalane-6a92938a','Annaalect','Senior BA','First Advantage','PO','Business Analyst to PM','Excellent',''),
('Susmit Dawade','https://www.linkedin.com/in/susmitdawade/','Reliance Nippon','Marketing Intern','Sunday Tech','APM','Marketing to PM','',''),
('Tanisha Varshney','https://www.linkedin.com/in/tanisha0810/','Fleek','PM','Bookee','PM','PM - PM','',''),
('Tej Gupta','https://www.linkedin.com/in/tej-gupta/','United Healthgroup','Consultant Business Systems','DMI','PM','Consultant to PM','',''),
('Tirthankar Guha Majumdar','https://www.linkedin.com/in/tirthankargm/','Schneider Electric','Business Intelligence Developer','Schneider Electric','TPM','Tech to PM','',''),
('Upendra Sharma','https://www.linkedin.com/in/upendrasharma1/','Homecredit India','SPM','Nagarro','PM','SPM to PM','',''),
('Urvesh Rathod','https://www.linkedin.com/in/urvesh-rathod-50a60151','Intech','PM','Quantified','SPM','PM to SPM','',''),
('Utkarsh Singh','https://www.linkedin.com/in/utkarsh-singh-13423973/','Open Financial','Data Analyst','Axis Mutual Fund','PM','Data Analyst to PM','',''),
('Venkata Padmavati Butukuri','https://www.linkedin.com/in/padmavati-butukuri-a6269280/','Ajira Tech','Senior BA','Incubyte','PM','Business Analyst to PM','',''),
('Vinay R S','https://www.linkedin.com/in/vinay-r-s-ba3837184/','User Umbrella','BA','ICICI Bank','PM','Business Analyst to PM','Average',''),
('Vishal Augustine','https://www.linkedin.com/in/vfawke/','ClearQuote','Customer Success','ClearQuote','PM','Customer Success to APM','',''),
('Rutuja Pujari','https://www.linkedin.com/in/rutuja-pujari/','Easebuzz','Software Engineer','Indify','PM','Tech to PM','',''),
('Lasitha E','https://www.linkedin.com/in/lasithae/','Inheaden','Software Engineer','HomeRun','APM','Tech to PM','',''),
('Gargi R Pathak','https://www.linkedin.com/in/gargipathak/','Capgemini','Senior Product Analyst','House of EdTech','PM','Product Analyst to PM','',''),
('Pradakshina TM','https://www.linkedin.com/in/pradakshina-tm-51b678180/','Rently','Software Developer','TechJays','APM','Tech to PM','',''),
('Mayank Joshi','https://www.linkedin.com/in/mayankjoshiddn/','Yojak','APM','Imarticus','APM','APM to APM','','')
ON CONFLICT DO NOTHING;
